# Generated by Django 5.0.6 on 2024-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=100)),
                ('summary', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
